### ISSUE TITLE
Make my own word list

### ISSUE THREAD

**Issue by wyliebutler** [modem7/react-wordle#106]
I'm new to this "thing".  I love what has been created here.   I am from Newfoundland, Canada.  We even have our own dictionary.  LOL  I have compiled a 650 word list that is unique to the Newfoundland dictionary.  I'd like to make a Newfoundland Wordle.  What parts of the project do I need to change?   Thanks in advance :-)

**Comment by modem7** [comment]
Heya!

The instructions for making your own fork with additional language inputs can be found here: https://github.com/cwackerfuss/react-wordle#how-can-i-create-a-version-in-another-language

Hope this helps!

**Comment by wyliebutler** [comment]
Thanks.  Will take a look :-). My first attempt was unsuccessful.   Will
have another go at it later today.  Thanks for the quick response.

Regards,

Wylie
