### ISSUE TITLE
What happened with latest version?

### ISSUE THREAD

**Issue by Danie10** [modem7/react-wordle#18]
Hi, my Wordle has been working great for a while, but obviously I pulled a new image today and got what looks like a "new" version? I figured out eventually from other issues logged that I need to change the container internal port from 80 to 8080.

It starts now, but does not seem to be on the same word of the day and my stats history seems to all be lost?  I did try pulling the legacy version, but that gave an error.  Is there some changelog here of what has actually changed, as it does not seem to only be the port number? This image was great as it was an exact clone of the original Wordle (without the NYT words removal).

**Comment by modem7** [comment]
Heya, what was the error for the legacy version?

I'll try to get around to doing a quick change log by end of day to better explain what has changed.

**Comment by modem7** [comment]
I've just added a [Changelog](https://github.com/modem7/react-wordle/blob/master/CHANGELOG.md)

**Comment by Danie10** [comment]
OK thanks, it was a 500 or 505 error seemed to be for grabbing the image. But I came right with linking to my legacy image that still existed my side so all working at least as it was before.

Seems though that the "latest" is in fact React-Wordle whilst the "legacy" is actually the original pre-NYT clone. So the two branches are essentially different. Latest is not just an update of "legacy".

**Comment by modem7** [comment]
That's correct Yupper!

I'll update the readme to make that clearer however!
