### ISSUE TITLE
Not available on web after rebuild

### ISSUE THREAD

**Issue by jeffreyswiggins** [modem7/react-wordle#7]
Attaching to Wordle
[36mWordle       |[0m 
[36mWordle       |[0m > game@0.1.0 start
[36mWordle       |[0m > react-scripts start
[36mWordle       |[0m 
[36mWordle       |[0m (node:24) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[36mWordle       |[0m (Use `node --trace-deprecation ...` to show where the warning was created)
[36mWordle       |[0m (node:24) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[36mWordle       |[0m Starting the development server...
[36mWordle       |[0m 
[36mWordle       |[0m Compiled successfully!
[36mWordle       |[0m 
[36mWordle       |[0m You can now view game in the browser.
[36mWordle       |[0m 
[36mWordle       |[0m   Local:            http://localhost:3000/react-wordle
[36mWordle       |[0m   On Your Network:  http://172.19.0.9:3000/react-wordle
[36mWordle       |[0m 
[36mWordle       |[0m Note that the development build is not optimized.
[36mWordle       |[0m To create a production build, use npm run build.
[36mWordle       |[0m 
[36mWordle       |[0m assets by path static/js/*.js 2.13 MiB
[36mWordle       |[0m   asset static/js/bundle.js 2.12 MiB [emitted] (name: main) 1 related asset
[36mWordle       |[0m   asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.91 KiB [emitted] 1 related asset
[36mWordle       |[0m asset index.html 1.72 KiB [emitted]
[36mWordle       |[0m asset asset-manifest.json 523 bytes [emitted]
[36mWordle       |[0m orphan modules 157 KiB [orphan] 227 modules
[36mWordle       |[0m runtime modules 31.3 KiB 16 modules
[36mWordle       |[0m cacheable modules 1.94 MiB
[36mWordle       |[0m   modules by path ./node_modules/ 1.64 MiB 101 modules
[36mWordle       |[0m   modules by path ./src/ 311 KiB
[36mWordle       |[0m     modules by path ./src/components/ 55.3 KiB 18 modules
[36mWordle       |[0m     modules by path ./src/lib/*.ts 13.4 KiB 5 modules
[36mWordle       |[0m     modules by path ./src/*.css 54.5 KiB 4 modules
[36mWordle       |[0m     modules by path ./src/constants/*.ts 170 KiB 4 modules
[36mWordle       |[0m     modules by path ./src/*.tsx 12.8 KiB
[36mWordle       |[0m       ./src/index.tsx 1.94 KiB [built] [code generated]
[36mWordle       |[0m       ./src/App.tsx 10.9 KiB [built] [code generated]
[36mWordle       |[0m     ./src/context/AlertContext.tsx 2.92 KiB [built] [code generated]
[36mWordle       |[0m     ./src/reportWebVitals.ts 1.36 KiB [built] [code generated]
[36mWordle       |[0m webpack 5.65.0 compiled successfully in 76314 ms
[36mWordle       |[0m No issues found.
[36mWordle       |[0m Compiling...
[36mWordle       |[0m Compiled successfully!
[36mWordle       |[0m assets by status 6.91 KiB [cached] 1 asset
[36mWordle       |[0m assets by chunk 2.12 MiB (name: main)
[36mWordle       |[0m   asset static/js/bundle.js 2.12 MiB [emitted] (name: main) 1 related asset
[36mWordle       |[0m   asset main.3217daddbc78f9a5ee4f.hot-update.js 355 bytes [emitted] [immutable] [hmr] (name: main) 1 related asset
[36mWordle       |[0m assets by path *.json 689 bytes
[36mWordle       |[0m   asset asset-manifest.json 661 bytes [emitted]
[36mWordle       |[0m   asset main.3217daddbc78f9a5ee4f.hot-update.json 28 bytes [emitted] [immutable] [hmr]
[36mWordle       |[0m asset index.html 1.72 KiB [emitted]
[36mWordle       |[0m Entrypoint main 2.12 MiB (2.13 MiB) = static/js/bundle.js 2.12 MiB main.3217daddbc78f9a5ee4f.hot-update.js 355 bytes 2 auxiliary assets
[36mWordle       |[0m cached modules 2.05 MiB [cached] 375 modules
[36mWordle       |[0m runtime modules 31.3 KiB 16 modules
[36mWordle       |[0m ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css 48.4 KiB [built]
[36mWordle       |[0m webpack 5.65.0 compiled successfully in 1082 ms
[36mWordle       |[0m No issues found.
[36mWordle       |[0m npm ERR! path /app
[36mWordle       |[0m npm ERR! command failed
[36mWordle       |[0m npm ERR! signal SIGTERM
[36mWordle       |[0m npm ERR! command sh -c react-scripts start
[36mWordle       |[0m 
[36mWordle       |[0m npm ERR! A complete log of this run can be found in:
[36mWordle       |[0m npm ERR!     /root/.npm/_logs/2022-03-16T21_20_23_494Z-debug-0.log
[36mWordle       |[0m 
[36mWordle       |[0m > game@0.1.0 start
[36mWordle       |[0m > react-scripts start
[36mWordle       |[0m 
[36mWordle       |[0m (node:27) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[36mWordle       |[0m (Use `node --trace-deprecation ...` to show where the warning was created)
[36mWordle       |[0m (node:27) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[36mWordle       |[0m Starting the development server...
[36mWordle       |[0m 
[36mWordle       |[0m Compiled successfully!
[36mWordle       |[0m 
[36mWordle       |[0m You can now view game in the browser.
[36mWordle       |[0m 
[36mWordle       |[0m   Local:            http://localhost:3000/react-wordle
[36mWordle       |[0m   On Your Network:  http://172.19.0.9:3000/react-wordle
[36mWordle       |[0m 
[36mWordle       |[0m Note that the development build is not optimized.
[36mWordle       |[0m To create a production build, use npm run build.
[36mWordle       |[0m 
[36mWordle       |[0m assets by path static/js/*.js 2.13 MiB
[36mWordle       |[0m   asset static/js/bundle.js 2.12 MiB [emitted] (name: main) 1 related asset
[36mWordle       |[0m   asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.91 KiB [emitted] 1 related asset
[36mWordle       |[0m asset index.html 1.72 KiB [emitted]
[36mWordle       |[0m asset asset-manifest.json 523 bytes [emitted]
[36mWordle       |[0m cached modules 2.09 MiB [cached] 376 modules
[36mWordle       |[0m runtime modules 31.3 KiB 16 modules
[36mWordle       |[0m webpack 5.65.0 compiled successfully in 5708 ms
[36mWordle       |[0m Files successfully emitted, waiting for typecheck results...
[36mWordle       |[0m Issues checking in progress...
[36mWordle       |[0m No issues found.

**Comment by modem7** [comment]
Sincerest apologies for this! 

There was a breaking change and an oversight on my part. 

Latest setup should be:

```yaml
version: "2.4"

services:

  wordle:
    image: modem7/wordle
    container_name: Wordle
    ports:
      - 80:8080
```

I'll try and get this fixed at some point so we're not just going to the node port and instead actually use NGINX properly. 

I've updated the readme to reflect this and will make sure to update and test more thoroughly once I roll out a proper patch.
