### ISSUE TITLE
Latest version blank page.

### ISSUE THREAD

**Issue by mariushosting** [modem7/react-wordle#92]
Latest version get a blank page.
Wordle is not working anymore with the latest docker version.

**Comment by modem7** [comment]
Heya,

Sorry about that, looks like there was a regression upstream.

I'm just making a new build which should resolve.

https://drone.modem7.com/modem7/react-wordle/59/1/3

Once that's completed, you should be able to pull down a new version and have it working.

**Comment by modem7** [comment]
@mariushosting please try now!

**Comment by mariushosting** [comment]
Thanks it's perfectly working right now!
